### ISSUE TITLE
Sorry in advance. Few Ideas

### ISSUE THREAD

**Issue by smclapes13** [Nchaos/ResearchSMU#175]
>Home left adjusted, schools center adjusted, login/register/logout left adjusted
>filter menu should be moved
>info needs to be placed on home screen
>filter menu for specific school should be open when you click that bar

THESE ARE FONTENOT IDEAS. DONT GET MAD AT ME

**Comment by Nchaos** [comment]
@smclapes13 login/register/logout left adjusted or right?
give me a description info for the home page and ill put it on
not sure what you mean by the filter stuff
