### ISSUE TITLE
Edit Sign in Info

### ISSUE THREAD

**Issue by Lorenzvonbibra** [Nchaos/ResearchSMU#25]
Change users information

**Comment by harshnormal** [comment]
Change the user's info how? Add things, remove? Give me more information.

**Comment by Nchaos** [comment]
I imagine its about changing email, password, name, etc

**Comment by Nchaos** [comment]
moving this to i3

**Comment by Nchaos** [comment]
HTTP Patch

**Comment by Nchaos** [comment]
@Lorenzvonbibra said he completed this so closing
