### ISSUE TITLE
Faculty Filter

### ISSUE THREAD

**Issue by Lorenzvonbibra** [Nchaos/ResearchSMU#31]
Search by faculty

**Comment by Nchaos** [comment]
moving this to i3
My idea is ill put a small search bar in the filter area and when you start typing a factulty member name it suggests auto completes and this will be part of the filter search

**Comment by Nchaos** [comment]
make a search result that looks up the faculty professors in the faculty user table from a json autocomplete
e.g.
Fon...
brings up
Mark Fontenot
Fontnkdjbds guy
somethingFon guy

**Comment by Nchaos** [comment]
closing because we have a function(untested) created
