### ISSUE TITLE
Navbar issues

### ISSUE THREAD

**Issue by DejayJD** [Nchaos/ResearchSMU#54]
First of all, the nav options pop up whenever you mouse over anywhere near them (like where the pop-up would be), instead of just when you mouse over the nav button itself. 
Because of this, I cant even click on the register or sign-in buttons.

Second of all, a white screen pops up at the bottom whenever your mouse leaves the nav pop-up. Happens every time
![whiteboxissue](https://cloud.githubusercontent.com/assets/6711655/6766696/e147f7b8-cfde-11e4-9d64-a6ccd8f66ab8.png)

Iteration 1 Testing. Tested on a 1920x1080 resolution. ~JD Francis (email: jdfrancis@smu.edu)

**Comment by Nariana** [comment]
To supplement, this is what one of the white spaces looks like.
![image](https://cloud.githubusercontent.com/assets/5320964/6773951/8129f1c0-d0e6-11e4-994b-c029184d08fa.png)
