### ISSUE TITLE
Testing Team Issue: Page Layout; Buttons Concern

### ISSUE THREAD

**Issue by ahavens** [Nchaos/ResearchSMU#56]
When I access the index.html from the downloaded zip file it loads on to the screen in the proper format, none of the buttons are bunched up. But when I access the IP address, 52.11.153.243, the entire layout gets smashed together. Such as the register button is on top of the sign in button. The school placement looks decent but the buttons are smashed together. I am using Mozilla Firefox but I highly doubt that makes a difference. This continually happens when I reload the IP address. 

![screen shot 2015-03-21 at 11 18 42 pm](https://cloud.githubusercontent.com/assets/6711518/6768028/48b8f7fc-d021-11e4-88c9-f47edc4436b1.png)

Contact: Aurora Havens
ahavens@smu.edu

**Comment by Nchaos** [comment]
fixed
